# Generated by Django 4.1.9 on 2023-06-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tasks_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='user_id',
            new_name='user',
        ),
    ]
